apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retro-arcade-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: retro-arcade.${EXTERNAL_IP}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retro-arcade-service
                port:
                  number: 3000
