# k8sgpt-servicemonitors.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8sgpt-results-exporter-sm
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: k8sgpt-results-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: false
# NOTE: No metricRelabelings here — scrape everything the exporter exposes.

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8sgpt-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: k8sgpt
  namespaceSelector:
    matchNames:
      - default
  jobLabel: k8sgpt_job
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: false
      metricRelabelings:
        - sourceLabels: ["__meta_kubernetes_service_name"]
          targetLabel: "service"
        - sourceLabels: ["__meta_kubernetes_namespace"]
          targetLabel: "namespace"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8sgpt-operator-sample-sm
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": "k8sgpt-sample"
  namespaceSelector:
    matchNames:
      - k8sgpt-operator-system
  jobLabel: k8sgpt_operator_job
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: false
      metricRelabelings:
        - sourceLabels: ["__meta_kubernetes_service_name"]
          targetLabel: "service"
        - sourceLabels: ["__meta_kubernetes_namespace"]
          targetLabel: "namespace"
