apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system-defaults
  namespace: kube-system
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "100m"
      memory: "200Mi"
    default:
      cpu: "200m"
      memory: "256Mi"
