# prometheus-values.yaml - for kube-prometheus-stack Helm chart (dev-friendly)
# Use:
# helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n default -f k8s/prometheus-values.yaml

prometheus:
  prometheusSpec:
    # Important: do not auto-scrape all ServiceMonitors; use an explicit selector
    serviceMonitorSelectorNilUsesHelmValues: false

    # Select ServiceMonitors with label release=prometheus (adjust if you used a different release name)
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

    # Allow Prometheus operator to discover ServiceMonitors in these namespaces
    # (use matchNames for widest CRD compatibility)
    serviceMonitorNamespaceSelector:
      matchNames:
        - default
        # - monitoring

    # Optional: reduce retention for dev/testing (set to production value when needed)
    retention: 7d
    evaluationInterval: "15s"

    # Run Prometheus behind a path-based ingress (/prometheus)
    # These flags ensure Prometheus serves and generates links under /prometheus
    additionalArgs:
      - --web.route-prefix=/prometheus
      - --web.external-url=/prometheus

    # If you want Prometheus web to listen only on certain ports / behave differently,
    # you can set additional containers/ports here (not usually required).

grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator

  # Serve Grafana from /grafana when using path-based Ingress
  env:
    GF_SERVER_ROOT_URL: /grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    # Optional: set GF_SERVER_EXTERNAL_URL if you have a full URL (ex: "https://example.com/grafana")
    # GF_SERVER_EXTERNAL_URL: "https://your.domain/grafana"

  ingress:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

  # Dev mode: persistence disabled. Enable in prod.
  persistence:
    enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

alertmanager:
  enabled: true

# Default resources — tweak for your cluster size
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
