## prometheus-values.yaml - for kube-prometheus-stack Helm chart (dev-friendly)
# Use this file with:
# helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f k8s/prometheus-values.yaml

prometheus:
  prometheusSpec:
    # Important: allow ServiceMonitors to be used (don't auto-scrape all ServiceMonitors)
    serviceMonitorSelectorNilUsesHelmValues: false
    # Optional: reduce retention for dev/testing (set to production value when needed)
    retention: 7d
    evaluationInterval: "15s"

grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator
  # Serve Grafana from /grafana when using path-based Ingress
  env:
    GF_SERVER_ROOT_URL: /grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  # Dev mode: persistence disabled. Enable in prod.
  persistence:
    enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

alertmanager:
  enabled: true

# Default resources — tweak for your cluster size
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
